#!/bin/bash
set -e

OS_BOUNDARY_LINE_DATA_SOURCE="https://api.os.uk/downloads/v1/products/BoundaryLine/downloads?area=GB&format=GeoPackage&redirect"

poetry run alembic upgrade head
MATERIALIZED_VIEW=iris.wind_driven_rain_projections_geojson TARGET_TABLE=wind_driven_rain_projections GPKG_SOURCE=https://services.arcgis.com/Lq3V5RFuTBC9I7kv/arcgis/rest/services/Annual_Index_of_Wind_Driven_Rain_Projections_5km/FeatureServer/replicafilescache/Annual_Index_of_Wind_Driven_Rain_Projections_5km_-6134910210859057092.gpkg GPKG_TABLE=Annual_Index_of_Wind_Driven_Rain___Projections__5km_ poetry run python developer-resources/load_gpkg_to_postgis.py
MATERIALIZED_VIEW=iris.icing_days_geojson TARGET_TABLE=annual_count_of_icing_days_1991_2020 GPKG_SOURCE=https://services.arcgis.com/Lq3V5RFuTBC9I7kv/arcgis/rest/services/Annual_Count_of_Icing_Days_1991_2020/FeatureServer/replicafilescache/Annual_Count_of_Icing_Days_1991_2020_5977951113111576455.gpkg GPKG_TABLE=annual_count_of_icing_days_1991_2020 poetry run python developer-resources/load_gpkg_to_postgis.py
MATERIALIZED_VIEW=iris.hot_summer_days_geojson TARGET_TABLE=annual_count_of_hot_summer_days_projections_12km GPKG_SOURCE=https://services.arcgis.com/Lq3V5RFuTBC9I7kv/arcgis/rest/services/Annual_Count_of_Hot_Days___Projections__12km_grid_/FeatureServer/replicafilescache/Annual_Count_of_Hot_Days___Projections__12km_grid__5151054028377652076.gpkg GPKG_TABLE=annual_count_of_hot_summer_days_projections_12km poetry run python developer-resources/load_gpkg_to_postgis.py
JOIN_VIEW=iris.uk_ward DATA_VIEW=iris.uk_ward_epc_data MATERIALIZED_VIEW=iris.uk_ward_epc TARGET_TABLE=district_borough_unitary_ward GPKG_SOURCE="$OS_BOUNDARY_LINE_DATA_SOURCE" GPKG_TABLE=district_borough_unitary_ward poetry run python developer-resources/load_gpkg_to_postgis.py
JOIN_VIEW=iris.uk_ward DATA_VIEW=iris.uk_ward_epc_data MATERIALIZED_VIEW=iris.uk_ward_epc TARGET_TABLE=unitary_electoral_division GPKG_SOURCE="${OS_BOUNDARY_LINE_DATA_SOURCE}" GPKG_TABLE=unitary_electoral_division poetry run python developer-resources/load_gpkg_to_postgis.py
JOIN_VIEW=iris.uk_region DATA_VIEW=iris.uk_region_epc_data MATERIALIZED_VIEW=iris.uk_region_epc TARGET_TABLE=scotland_and_wales_region GPKG_SOURCE="$OS_BOUNDARY_LINE_DATA_SOURCE" GPKG_TABLE=scotland_and_wales_region poetry run python developer-resources/load_gpkg_to_postgis.py
JOIN_VIEW=iris.uk_region DATA_VIEW=iris.uk_region_epc_data MATERIALIZED_VIEW=iris.uk_region_epc TARGET_TABLE=english_region GPKG_SOURCE="$OS_BOUNDARY_LINE_DATA_SOURCE" GPKG_TABLE=english_region poetry run python developer-resources/load_gpkg_to_postgis.py
DATA_VIEW=iris.district_borough_unitary_epc_data MATERIALIZED_VIEW=iris.district_borough_unitary_epc TARGET_TABLE=district_borough_unitary GPKG_SOURCE="$OS_BOUNDARY_LINE_DATA_SOURCE" GPKG_TABLE=district_borough_unitary poetry run python developer-resources/load_gpkg_to_postgis.py
DATA_VIEW=iris.boundary_line_ceremonial_counties_epc_data MATERIALIZED_VIEW=iris.boundary_line_ceremonial_counties_epc TARGET_TABLE=boundary_line_ceremonial_counties GPKG_SOURCE="$OS_BOUNDARY_LINE_DATA_SOURCE" GPKG_TABLE=boundary_line_ceremonial_counties poetry run python developer-resources/load_gpkg_to_postgis.py
TARGET_TABLE=country_region GPKG_SOURCE="$OS_BOUNDARY_LINE_DATA_SOURCE" GPKG_TABLE=country_region poetry run python developer-resources/load_gpkg_to_postgis.py
poetry run python developer-resources/sync_region_fks_dbu.py
poetry run python api/main.py --host 0.0.0.0
