# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

name: Backend CI on PR

on:
  workflow_call:
    secrets:
      GH_PACKAGES_PAT:
        required: true
  pull_request:
    branches:
      - "develop"
    paths:
      - "backend/api/**"
      - "backend/requirements.txt"
      - ".github/workflows/backend-ci-pr.yml"
      - ".github/workflows/backend-cd-pr-merge.yml"
  workflow_dispatch:

jobs:
  security-scanning:
    permissions:
      contents: read
      packages: read
      statuses: write # To report GitHub Actions status checks
    name: Security Scanning
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
        with:
          scan-type: "fs"
          scan-ref: .
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
        continue-on-error: true

  unit-tests:
    permissions:
      contents: read
      packages: read
      statuses: write # To report GitHub Actions status checks
    name: Run Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GH_PACKAGES_PAT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          cp backend/pyproject.toml .
          cp backend/poetry.lock .
          python -m pip install poetry
          poetry install --only main --no-root
          poetry run pip install --upgrade pip
          poetry run pip install -r backend/requirements-private.txt

      - name: Run unit tests
        run: poetry run pytest backend/unit_tests/ -v

  docker-build-test-scan:
    permissions:
      contents: read
      packages: read
      statuses: write # To report GitHub Actions status checks
    name: Build, Docker Build, Test & Scan
    runs-on: ubuntu-latest
    needs: [security-scanning, unit-tests]
    timeout-minutes: 20
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GH_PACKAGES_PAT }}
    environment: development
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build --secret id=pat_token,env=GITHUB_ACCESS_TOKEN -t iris/api:latest -f backend/Dockerfile backend

      - name: Run Trivy Scan on Docker Image
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
        with:
          image-ref: "iris/api:latest"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
        continue-on-error: true
