apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-csv-postgres-importer-config-map
  namespace: iris
data:
  DB_HOST: "{REPLACE_ME}"
  DB_PORT: "{REPLACE_ME}"
  DB_NAME: "{REPLACE_ME}"
  AWS_REGION: "{REPLACE_ME}"
